module Geos
  @[Link(ldflags: "`command -v pkg-config > /dev/null && pkg-config --libs geos 2> /dev/null|| printf %s '-lgeos'`")]
  lib Lib
    GEOS_CAPI_VERSION_MAJOR =  1
    GEOS_CAPI_VERSION_MINOR = 16
    GEOS_CAPI_VERSION_PATCH =  2
    GEOS_VERSION_MAJOR      =  3
    GEOS_VERSION_MINOR      =  9
    GEOS_VERSION_PATCH      =  0
    alias GeosBufParamsT = Void
    alias GeosContextHandleHs = Void
    alias GeosCoordSeqT = Void
    alias GeosDistanceCallback = (Void*, Void*, LibC::Double*, Void* -> LibC::Int)
    alias GeosGeomT = Void
    alias GeosMessageHandler = (LibC::Char* -> Void)
    alias GeosMessageHandlerR = (LibC::Char*, Void* -> Void)
    alias GeosPrepGeomT = Void
    alias GeosQueryCallback = (Void*, Void* -> Void)
    alias GeosstRtreeT = Void
    alias GeoswkbReaderT = Void
    alias GeoswkbWriterT = Void
    alias GeoswktReaderT = Void
    alias GeoswktWriterT = Void
    fun geo_sis_closed = GEOSisClosed(g : GeosGeometry) : LibC::Char
    fun geo_sis_closed_r = GEOSisClosed_r(handle : GeosContextHandleT, g : GeosGeometry) : LibC::Char
    fun geo_sis_empty = GEOSisEmpty(g : GeosGeometry) : LibC::Char
    fun geo_sis_empty_r = GEOSisEmpty_r(handle : GeosContextHandleT, g : GeosGeometry) : LibC::Char
    fun geo_sis_ring = GEOSisRing(g : GeosGeometry) : LibC::Char
    fun geo_sis_ring_r = GEOSisRing_r(handle : GeosContextHandleT, g : GeosGeometry) : LibC::Char
    fun geo_sis_simple = GEOSisSimple(g : GeosGeometry) : LibC::Char
    fun geo_sis_simple_r = GEOSisSimple_r(handle : GeosContextHandleT, g : GeosGeometry) : LibC::Char
    fun geo_sis_valid = GEOSisValid(g : GeosGeometry) : LibC::Char
    fun geo_sis_valid_detail = GEOSisValidDetail(g : GeosGeometry, flags : LibC::Int, reason : LibC::Char**, location : GeosGeometry*) : LibC::Char
    fun geo_sis_valid_detail_r = GEOSisValidDetail_r(handle : GeosContextHandleT, g : GeosGeometry, flags : LibC::Int, reason : LibC::Char**, location : GeosGeometry*) : LibC::Char
    fun geo_sis_valid_r = GEOSisValid_r(handle : GeosContextHandleT, g : GeosGeometry) : LibC::Char
    fun geo_sis_valid_reason = GEOSisValidReason(g : GeosGeometry) : LibC::Char*
    fun geo_sis_valid_reason_r = GEOSisValidReason_r(handle : GeosContextHandleT, g : GeosGeometry) : LibC::Char*
    fun geo_sversion = GEOSversion : LibC::Char*
    fun geos_area = GEOSArea(g : GeosGeometry, area : LibC::Double*) : LibC::Int
    fun geos_area_r = GEOSArea_r(handle : GeosContextHandleT, g : GeosGeometry, area : LibC::Double*) : LibC::Int
    fun geos_boundary = GEOSBoundary(g : GeosGeometry) : GeosGeometry
    fun geos_boundary_r = GEOSBoundary_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_buffer = GEOSBuffer(g : GeosGeometry, width : LibC::Double, quadsegs : LibC::Int) : GeosGeometry
    fun geos_buffer_params_create = GEOSBufferParams_create : GeosBufferParams
    fun geos_buffer_params_create_r = GEOSBufferParams_create_r(handle : GeosContextHandleT) : GeosBufferParams
    fun geos_buffer_params_destroy = GEOSBufferParams_destroy(parms : GeosBufferParams)
    fun geos_buffer_params_destroy_r = GEOSBufferParams_destroy_r(handle : GeosContextHandleT, parms : GeosBufferParams)
    fun geos_buffer_params_set_end_cap_style = GEOSBufferParams_setEndCapStyle(p : GeosBufferParams, style : LibC::Int) : LibC::Int
    fun geos_buffer_params_set_end_cap_style_r = GEOSBufferParams_setEndCapStyle_r(handle : GeosContextHandleT, p : GeosBufferParams, style : LibC::Int) : LibC::Int
    fun geos_buffer_params_set_join_style = GEOSBufferParams_setJoinStyle(p : GeosBufferParams, join_style : LibC::Int) : LibC::Int
    fun geos_buffer_params_set_join_style_r = GEOSBufferParams_setJoinStyle_r(handle : GeosContextHandleT, p : GeosBufferParams, join_style : LibC::Int) : LibC::Int
    fun geos_buffer_params_set_mitre_limit = GEOSBufferParams_setMitreLimit(p : GeosBufferParams, mitre_limit : LibC::Double) : LibC::Int
    fun geos_buffer_params_set_mitre_limit_r = GEOSBufferParams_setMitreLimit_r(handle : GeosContextHandleT, p : GeosBufferParams, mitre_limit : LibC::Double) : LibC::Int
    fun geos_buffer_params_set_quadrant_segments = GEOSBufferParams_setQuadrantSegments(p : GeosBufferParams, quad_segs : LibC::Int) : LibC::Int
    fun geos_buffer_params_set_quadrant_segments_r = GEOSBufferParams_setQuadrantSegments_r(handle : GeosContextHandleT, p : GeosBufferParams, quad_segs : LibC::Int) : LibC::Int
    fun geos_buffer_params_set_single_sided = GEOSBufferParams_setSingleSided(p : GeosBufferParams, single_sided : LibC::Int) : LibC::Int
    fun geos_buffer_params_set_single_sided_r = GEOSBufferParams_setSingleSided_r(handle : GeosContextHandleT, p : GeosBufferParams, single_sided : LibC::Int) : LibC::Int
    fun geos_buffer_r = GEOSBuffer_r(handle : GeosContextHandleT, g : GeosGeometry, width : LibC::Double, quadsegs : LibC::Int) : GeosGeometry
    fun geos_buffer_with_params = GEOSBufferWithParams(g : GeosGeometry, p : GeosBufferParams, width : LibC::Double) : GeosGeometry
    fun geos_buffer_with_params_r = GEOSBufferWithParams_r(handle : GeosContextHandleT, g : GeosGeometry, p : GeosBufferParams, width : LibC::Double) : GeosGeometry
    fun geos_buffer_with_style = GEOSBufferWithStyle(g : GeosGeometry, width : LibC::Double, quadsegs : LibC::Int, end_cap_style : LibC::Int, join_style : LibC::Int, mitre_limit : LibC::Double) : GeosGeometry
    fun geos_buffer_with_style_r = GEOSBufferWithStyle_r(handle : GeosContextHandleT, g : GeosGeometry, width : LibC::Double, quadsegs : LibC::Int, end_cap_style : LibC::Int, join_style : LibC::Int, mitre_limit : LibC::Double) : GeosGeometry
    fun geos_build_area = GEOSBuildArea(g : GeosGeometry) : GeosGeometry
    fun geos_build_area_r = GEOSBuildArea_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_clip_by_rect = GEOSClipByRect(g : GeosGeometry, xmin : LibC::Double, ymin : LibC::Double, xmax : LibC::Double, ymax : LibC::Double) : GeosGeometry
    fun geos_clip_by_rect_r = GEOSClipByRect_r(handle : GeosContextHandleT, g : GeosGeometry, xmin : LibC::Double, ymin : LibC::Double, xmax : LibC::Double, ymax : LibC::Double) : GeosGeometry
    fun geos_contains = GEOSContains(g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_contains_r = GEOSContains_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_context_set_error_handler_r = GEOSContext_setErrorHandler_r(ext_handle : GeosContextHandleT, ef : GeosMessageHandler) : GeosMessageHandler
    fun geos_context_set_error_message_handler_r = GEOSContext_setErrorMessageHandler_r(ext_handle : GeosContextHandleT, ef : GeosMessageHandlerR, user_data : Void*) : GeosMessageHandlerR
    fun geos_context_set_notice_handler_r = GEOSContext_setNoticeHandler_r(ext_handle : GeosContextHandleT, nf : GeosMessageHandler) : GeosMessageHandler
    fun geos_context_set_notice_message_handler_r = GEOSContext_setNoticeMessageHandler_r(ext_handle : GeosContextHandleT, nf : GeosMessageHandlerR, user_data : Void*) : GeosMessageHandlerR
    fun geos_convex_hull = GEOSConvexHull(g : GeosGeometry) : GeosGeometry
    fun geos_convex_hull_r = GEOSConvexHull_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_coord_seq_clone = GEOSCoordSeq_clone(s : GeosCoordSequence) : GeosCoordSequence
    fun geos_coord_seq_clone_r = GEOSCoordSeq_clone_r(handle : GeosContextHandleT, s : GeosCoordSequence) : GeosCoordSequence
    fun geos_coord_seq_create = GEOSCoordSeq_create(size : LibC::UInt, dims : LibC::UInt) : GeosCoordSequence
    fun geos_coord_seq_create_r = GEOSCoordSeq_create_r(handle : GeosContextHandleT, size : LibC::UInt, dims : LibC::UInt) : GeosCoordSequence
    fun geos_coord_seq_destroy = GEOSCoordSeq_destroy(s : GeosCoordSequence)
    fun geos_coord_seq_destroy_r = GEOSCoordSeq_destroy_r(handle : GeosContextHandleT, s : GeosCoordSequence)
    fun geos_coord_seq_get_dimensions = GEOSCoordSeq_getDimensions(s : GeosCoordSequence, dims : LibC::UInt*) : LibC::Int
    fun geos_coord_seq_get_dimensions_r = GEOSCoordSeq_getDimensions_r(handle : GeosContextHandleT, s : GeosCoordSequence, dims : LibC::UInt*) : LibC::Int
    fun geos_coord_seq_get_ordinate = GEOSCoordSeq_getOrdinate(s : GeosCoordSequence, idx : LibC::UInt, dim : LibC::UInt, val : LibC::Double*) : LibC::Int
    fun geos_coord_seq_get_ordinate_r = GEOSCoordSeq_getOrdinate_r(handle : GeosContextHandleT, s : GeosCoordSequence, idx : LibC::UInt, dim : LibC::UInt, val : LibC::Double*) : LibC::Int
    fun geos_coord_seq_get_size = GEOSCoordSeq_getSize(s : GeosCoordSequence, size : LibC::UInt*) : LibC::Int
    fun geos_coord_seq_get_size_r = GEOSCoordSeq_getSize_r(handle : GeosContextHandleT, s : GeosCoordSequence, size : LibC::UInt*) : LibC::Int
    fun geos_coord_seq_get_x = GEOSCoordSeq_getX(s : GeosCoordSequence, idx : LibC::UInt, val : LibC::Double*) : LibC::Int
    fun geos_coord_seq_get_x_r = GEOSCoordSeq_getX_r(handle : GeosContextHandleT, s : GeosCoordSequence, idx : LibC::UInt, val : LibC::Double*) : LibC::Int
    fun geos_coord_seq_get_xy = GEOSCoordSeq_getXY(s : GeosCoordSequence, idx : LibC::UInt, x : LibC::Double*, y : LibC::Double*) : LibC::Int
    fun geos_coord_seq_get_xy_r = GEOSCoordSeq_getXY_r(handle : GeosContextHandleT, s : GeosCoordSequence, idx : LibC::UInt, x : LibC::Double*, y : LibC::Double*) : LibC::Int
    fun geos_coord_seq_get_xyz = GEOSCoordSeq_getXYZ(s : GeosCoordSequence, idx : LibC::UInt, x : LibC::Double*, y : LibC::Double*, z : LibC::Double*) : LibC::Int
    fun geos_coord_seq_get_xyz_r = GEOSCoordSeq_getXYZ_r(handle : GeosContextHandleT, s : GeosCoordSequence, idx : LibC::UInt, x : LibC::Double*, y : LibC::Double*, z : LibC::Double*) : LibC::Int
    fun geos_coord_seq_get_y = GEOSCoordSeq_getY(s : GeosCoordSequence, idx : LibC::UInt, val : LibC::Double*) : LibC::Int
    fun geos_coord_seq_get_y_r = GEOSCoordSeq_getY_r(handle : GeosContextHandleT, s : GeosCoordSequence, idx : LibC::UInt, val : LibC::Double*) : LibC::Int
    fun geos_coord_seq_get_z = GEOSCoordSeq_getZ(s : GeosCoordSequence, idx : LibC::UInt, val : LibC::Double*) : LibC::Int
    fun geos_coord_seq_get_z_r = GEOSCoordSeq_getZ_r(handle : GeosContextHandleT, s : GeosCoordSequence, idx : LibC::UInt, val : LibC::Double*) : LibC::Int
    fun geos_coord_seq_is_ccw = GEOSCoordSeq_isCCW(s : GeosCoordSequence, is_ccw : LibC::Char*) : LibC::Int
    fun geos_coord_seq_is_ccw_r = GEOSCoordSeq_isCCW_r(handle : GeosContextHandleT, s : GeosCoordSequence, is_ccw : LibC::Char*) : LibC::Int
    fun geos_coord_seq_set_ordinate = GEOSCoordSeq_setOrdinate(s : GeosCoordSequence, idx : LibC::UInt, dim : LibC::UInt, val : LibC::Double) : LibC::Int
    fun geos_coord_seq_set_ordinate_r = GEOSCoordSeq_setOrdinate_r(handle : GeosContextHandleT, s : GeosCoordSequence, idx : LibC::UInt, dim : LibC::UInt, val : LibC::Double) : LibC::Int
    fun geos_coord_seq_set_x = GEOSCoordSeq_setX(s : GeosCoordSequence, idx : LibC::UInt, val : LibC::Double) : LibC::Int
    fun geos_coord_seq_set_x_r = GEOSCoordSeq_setX_r(handle : GeosContextHandleT, s : GeosCoordSequence, idx : LibC::UInt, val : LibC::Double) : LibC::Int
    fun geos_coord_seq_set_xy = GEOSCoordSeq_setXY(s : GeosCoordSequence, idx : LibC::UInt, x : LibC::Double, y : LibC::Double) : LibC::Int
    fun geos_coord_seq_set_xy_r = GEOSCoordSeq_setXY_r(handle : GeosContextHandleT, s : GeosCoordSequence, idx : LibC::UInt, x : LibC::Double, y : LibC::Double) : LibC::Int
    fun geos_coord_seq_set_xyz = GEOSCoordSeq_setXYZ(s : GeosCoordSequence, idx : LibC::UInt, x : LibC::Double, y : LibC::Double, z : LibC::Double) : LibC::Int
    fun geos_coord_seq_set_xyz_r = GEOSCoordSeq_setXYZ_r(handle : GeosContextHandleT, s : GeosCoordSequence, idx : LibC::UInt, x : LibC::Double, y : LibC::Double, z : LibC::Double) : LibC::Int
    fun geos_coord_seq_set_y = GEOSCoordSeq_setY(s : GeosCoordSequence, idx : LibC::UInt, val : LibC::Double) : LibC::Int
    fun geos_coord_seq_set_y_r = GEOSCoordSeq_setY_r(handle : GeosContextHandleT, s : GeosCoordSequence, idx : LibC::UInt, val : LibC::Double) : LibC::Int
    fun geos_coord_seq_set_z = GEOSCoordSeq_setZ(s : GeosCoordSequence, idx : LibC::UInt, val : LibC::Double) : LibC::Int
    fun geos_coord_seq_set_z_r = GEOSCoordSeq_setZ_r(handle : GeosContextHandleT, s : GeosCoordSequence, idx : LibC::UInt, val : LibC::Double) : LibC::Int
    fun geos_coverage_union = GEOSCoverageUnion(g : GeosGeometry) : GeosGeometry
    fun geos_coverage_union_r = GEOSCoverageUnion_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_covered_by = GEOSCoveredBy(g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_covered_by_r = GEOSCoveredBy_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_covers = GEOSCovers(g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_covers_r = GEOSCovers_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_crosses = GEOSCrosses(g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_crosses_r = GEOSCrosses_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_delaunay_triangulation = GEOSDelaunayTriangulation(g : GeosGeometry, tolerance : LibC::Double, only_edges : LibC::Int) : GeosGeometry
    fun geos_delaunay_triangulation_r = GEOSDelaunayTriangulation_r(handle : GeosContextHandleT, g : GeosGeometry, tolerance : LibC::Double, only_edges : LibC::Int) : GeosGeometry
    fun geos_difference = GEOSDifference(g1 : GeosGeometry, g2 : GeosGeometry) : GeosGeometry
    fun geos_difference_prec = GEOSDifferencePrec(g1 : GeosGeometry, g2 : GeosGeometry, grid_size : LibC::Double) : GeosGeometry
    fun geos_difference_prec_r = GEOSDifferencePrec_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry, grid_size : LibC::Double) : GeosGeometry
    fun geos_difference_r = GEOSDifference_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry) : GeosGeometry
    fun geos_disjoint = GEOSDisjoint(g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_disjoint_r = GEOSDisjoint_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_distance = GEOSDistance(g1 : GeosGeometry, g2 : GeosGeometry, dist : LibC::Double*) : LibC::Int
    fun geos_distance_indexed = GEOSDistanceIndexed(g1 : GeosGeometry, g2 : GeosGeometry, dist : LibC::Double*) : LibC::Int
    fun geos_distance_indexed_r = GEOSDistanceIndexed_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry, dist : LibC::Double*) : LibC::Int
    fun geos_distance_r = GEOSDistance_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry, dist : LibC::Double*) : LibC::Int
    fun geos_envelope = GEOSEnvelope(g : GeosGeometry) : GeosGeometry
    fun geos_envelope_r = GEOSEnvelope_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_equals = GEOSEquals(g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_equals_exact = GEOSEqualsExact(g1 : GeosGeometry, g2 : GeosGeometry, tolerance : LibC::Double) : LibC::Char
    fun geos_equals_exact_r = GEOSEqualsExact_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry, tolerance : LibC::Double) : LibC::Char
    fun geos_equals_r = GEOSEquals_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_finish_r = GEOS_finish_r(handle : GeosContextHandleT)
    fun geos_frechet_distance = GEOSFrechetDistance(g1 : GeosGeometry, g2 : GeosGeometry, dist : LibC::Double*) : LibC::Int
    fun geos_frechet_distance_densify = GEOSFrechetDistanceDensify(g1 : GeosGeometry, g2 : GeosGeometry, densify_frac : LibC::Double, dist : LibC::Double*) : LibC::Int
    fun geos_frechet_distance_densify_r = GEOSFrechetDistanceDensify_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry, densify_frac : LibC::Double, dist : LibC::Double*) : LibC::Int
    fun geos_frechet_distance_r = GEOSFrechetDistance_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry, dist : LibC::Double*) : LibC::Int
    fun geos_free = GEOSFree(buffer : Void*)
    fun geos_free_r = GEOSFree_r(handle : GeosContextHandleT, buffer : Void*)
    fun geos_geom_clone = GEOSGeom_clone(g : GeosGeometry) : GeosGeometry
    fun geos_geom_clone_r = GEOSGeom_clone_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_geom_create_collection = GEOSGeom_createCollection(type : LibC::Int, geoms : GeosGeometry*, ngeoms : LibC::UInt) : GeosGeometry
    fun geos_geom_create_collection_r = GEOSGeom_createCollection_r(handle : GeosContextHandleT, type : LibC::Int, geoms : GeosGeometry*, ngeoms : LibC::UInt) : GeosGeometry
    fun geos_geom_create_empty_collection = GEOSGeom_createEmptyCollection(type : LibC::Int) : GeosGeometry
    fun geos_geom_create_empty_collection_r = GEOSGeom_createEmptyCollection_r(handle : GeosContextHandleT, type : LibC::Int) : GeosGeometry
    fun geos_geom_create_empty_line_string = GEOSGeom_createEmptyLineString : GeosGeometry
    fun geos_geom_create_empty_line_string_r = GEOSGeom_createEmptyLineString_r(handle : GeosContextHandleT) : GeosGeometry
    fun geos_geom_create_empty_point = GEOSGeom_createEmptyPoint : GeosGeometry
    fun geos_geom_create_empty_point_r = GEOSGeom_createEmptyPoint_r(handle : GeosContextHandleT) : GeosGeometry
    fun geos_geom_create_empty_polygon = GEOSGeom_createEmptyPolygon : GeosGeometry
    fun geos_geom_create_empty_polygon_r = GEOSGeom_createEmptyPolygon_r(handle : GeosContextHandleT) : GeosGeometry
    fun geos_geom_create_line_string = GEOSGeom_createLineString(s : GeosCoordSequence) : GeosGeometry
    fun geos_geom_create_line_string_r = GEOSGeom_createLineString_r(handle : GeosContextHandleT, s : GeosCoordSequence) : GeosGeometry
    fun geos_geom_create_linear_ring = GEOSGeom_createLinearRing(s : GeosCoordSequence) : GeosGeometry
    fun geos_geom_create_linear_ring_r = GEOSGeom_createLinearRing_r(handle : GeosContextHandleT, s : GeosCoordSequence) : GeosGeometry
    fun geos_geom_create_point = GEOSGeom_createPoint(s : GeosCoordSequence) : GeosGeometry
    fun geos_geom_create_point_from_xy = GEOSGeom_createPointFromXY(x : LibC::Double, y : LibC::Double) : GeosGeometry
    fun geos_geom_create_point_from_xy_r = GEOSGeom_createPointFromXY_r(handle : GeosContextHandleT, x : LibC::Double, y : LibC::Double) : GeosGeometry
    fun geos_geom_create_point_r = GEOSGeom_createPoint_r(handle : GeosContextHandleT, s : GeosCoordSequence) : GeosGeometry
    fun geos_geom_create_polygon = GEOSGeom_createPolygon(shell : GeosGeometry, holes : GeosGeometry*, nholes : LibC::UInt) : GeosGeometry
    fun geos_geom_create_polygon_r = GEOSGeom_createPolygon_r(handle : GeosContextHandleT, shell : GeosGeometry, holes : GeosGeometry*, nholes : LibC::UInt) : GeosGeometry
    fun geos_geom_destroy = GEOSGeom_destroy(g : GeosGeometry)
    fun geos_geom_destroy_r = GEOSGeom_destroy_r(handle : GeosContextHandleT, g : GeosGeometry)
    fun geos_geom_extract_unique_points = GEOSGeom_extractUniquePoints(g : GeosGeometry) : GeosGeometry
    fun geos_geom_extract_unique_points_r = GEOSGeom_extractUniquePoints_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_geom_from_hex_buf = GEOSGeomFromHEX_buf(hex : UInt8*, size : LibC::SizeT) : GeosGeometry
    fun geos_geom_from_hex_buf_r = GEOSGeomFromHEX_buf_r(handle : GeosContextHandleT, hex : UInt8*, size : LibC::SizeT) : GeosGeometry
    fun geos_geom_from_wkb_buf = GEOSGeomFromWKB_buf(wkb : UInt8*, size : LibC::SizeT) : GeosGeometry
    fun geos_geom_from_wkb_buf_r = GEOSGeomFromWKB_buf_r(handle : GeosContextHandleT, wkb : UInt8*, size : LibC::SizeT) : GeosGeometry
    fun geos_geom_from_wkt = GEOSGeomFromWKT(wkt : LibC::Char*) : GeosGeometry
    fun geos_geom_from_wkt_r = GEOSGeomFromWKT_r(handle : GeosContextHandleT, wkt : LibC::Char*) : GeosGeometry
    fun geos_geom_get_coord_seq = GEOSGeom_getCoordSeq(g : GeosGeometry) : GeosCoordSequence
    fun geos_geom_get_coord_seq_r = GEOSGeom_getCoordSeq_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosCoordSequence
    fun geos_geom_get_coordinate_dimension = GEOSGeom_getCoordinateDimension(g : GeosGeometry) : LibC::Int
    fun geos_geom_get_coordinate_dimension_r = GEOSGeom_getCoordinateDimension_r(handle : GeosContextHandleT, g : GeosGeometry) : LibC::Int
    fun geos_geom_get_dimensions = GEOSGeom_getDimensions(g : GeosGeometry) : LibC::Int
    fun geos_geom_get_dimensions_r = GEOSGeom_getDimensions_r(handle : GeosContextHandleT, g : GeosGeometry) : LibC::Int
    fun geos_geom_get_end_point = GEOSGeomGetEndPoint(g : GeosGeometry) : GeosGeometry
    fun geos_geom_get_end_point_r = GEOSGeomGetEndPoint_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_geom_get_length = GEOSGeomGetLength(g : GeosGeometry, length : LibC::Double*) : LibC::Int
    fun geos_geom_get_length_r = GEOSGeomGetLength_r(handle : GeosContextHandleT, g : GeosGeometry, length : LibC::Double*) : LibC::Int
    fun geos_geom_get_num_points = GEOSGeomGetNumPoints(g : GeosGeometry) : LibC::Int
    fun geos_geom_get_num_points_r = GEOSGeomGetNumPoints_r(handle : GeosContextHandleT, g : GeosGeometry) : LibC::Int
    fun geos_geom_get_point_n = GEOSGeomGetPointN(g : GeosGeometry, n : LibC::Int) : GeosGeometry
    fun geos_geom_get_point_n_r = GEOSGeomGetPointN_r(handle : GeosContextHandleT, g : GeosGeometry, n : LibC::Int) : GeosGeometry
    fun geos_geom_get_precision = GEOSGeom_getPrecision(g : GeosGeometry) : LibC::Double
    fun geos_geom_get_precision_r = GEOSGeom_getPrecision_r(handle : GeosContextHandleT, g : GeosGeometry) : LibC::Double
    fun geos_geom_get_start_point = GEOSGeomGetStartPoint(g : GeosGeometry) : GeosGeometry
    fun geos_geom_get_start_point_r = GEOSGeomGetStartPoint_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_geom_get_user_data = GEOSGeom_getUserData(g : GeosGeometry) : Void*
    fun geos_geom_get_user_data_r = GEOSGeom_getUserData_r(handle : GeosContextHandleT, g : GeosGeometry) : Void*
    fun geos_geom_get_x = GEOSGeomGetX(g : GeosGeometry, x : LibC::Double*) : LibC::Int
    fun geos_geom_get_x_max = GEOSGeom_getXMax(g : GeosGeometry, value : LibC::Double*) : LibC::Int
    fun geos_geom_get_x_max_r = GEOSGeom_getXMax_r(handle : GeosContextHandleT, g : GeosGeometry, value : LibC::Double*) : LibC::Int
    fun geos_geom_get_x_min = GEOSGeom_getXMin(g : GeosGeometry, value : LibC::Double*) : LibC::Int
    fun geos_geom_get_x_min_r = GEOSGeom_getXMin_r(handle : GeosContextHandleT, g : GeosGeometry, value : LibC::Double*) : LibC::Int
    fun geos_geom_get_x_r = GEOSGeomGetX_r(handle : GeosContextHandleT, g : GeosGeometry, x : LibC::Double*) : LibC::Int
    fun geos_geom_get_y = GEOSGeomGetY(g : GeosGeometry, y : LibC::Double*) : LibC::Int
    fun geos_geom_get_y_max = GEOSGeom_getYMax(g : GeosGeometry, value : LibC::Double*) : LibC::Int
    fun geos_geom_get_y_max_r = GEOSGeom_getYMax_r(handle : GeosContextHandleT, g : GeosGeometry, value : LibC::Double*) : LibC::Int
    fun geos_geom_get_y_min = GEOSGeom_getYMin(g : GeosGeometry, value : LibC::Double*) : LibC::Int
    fun geos_geom_get_y_min_r = GEOSGeom_getYMin_r(handle : GeosContextHandleT, g : GeosGeometry, value : LibC::Double*) : LibC::Int
    fun geos_geom_get_y_r = GEOSGeomGetY_r(handle : GeosContextHandleT, g : GeosGeometry, y : LibC::Double*) : LibC::Int
    fun geos_geom_get_z = GEOSGeomGetZ(g : GeosGeometry, z : LibC::Double*) : LibC::Int
    fun geos_geom_get_z_r = GEOSGeomGetZ_r(handle : GeosContextHandleT, g : GeosGeometry, z : LibC::Double*) : LibC::Int
    fun geos_geom_set_precision = GEOSGeom_setPrecision(g : GeosGeometry, grid_size : LibC::Double, flags : LibC::Int) : GeosGeometry
    fun geos_geom_set_precision_r = GEOSGeom_setPrecision_r(handle : GeosContextHandleT, g : GeosGeometry, grid_size : LibC::Double, flags : LibC::Int) : GeosGeometry
    fun geos_geom_set_user_data = GEOSGeom_setUserData(g : GeosGeometry, user_data : Void*)
    fun geos_geom_set_user_data_r = GEOSGeom_setUserData_r(handle : GeosContextHandleT, g : GeosGeometry, user_data : Void*)
    fun geos_geom_to_hex_buf = GEOSGeomToHEX_buf(g : GeosGeometry, size : LibC::SizeT*) : UInt8*
    fun geos_geom_to_hex_buf_r = GEOSGeomToHEX_buf_r(handle : GeosContextHandleT, g : GeosGeometry, size : LibC::SizeT*) : UInt8*
    fun geos_geom_to_wkb_buf = GEOSGeomToWKB_buf(g : GeosGeometry, size : LibC::SizeT*) : UInt8*
    fun geos_geom_to_wkb_buf_r = GEOSGeomToWKB_buf_r(handle : GeosContextHandleT, g : GeosGeometry, size : LibC::SizeT*) : UInt8*
    fun geos_geom_to_wkt = GEOSGeomToWKT(g : GeosGeometry) : LibC::Char*
    fun geos_geom_to_wkt_r = GEOSGeomToWKT_r(handle : GeosContextHandleT, g : GeosGeometry) : LibC::Char*
    fun geos_geom_type = GEOSGeomType(g : GeosGeometry) : LibC::Char*
    fun geos_geom_type_id = GEOSGeomTypeId(g : GeosGeometry) : LibC::Int
    fun geos_geom_type_id_r = GEOSGeomTypeId_r(handle : GeosContextHandleT, g : GeosGeometry) : LibC::Int
    fun geos_geom_type_r = GEOSGeomType_r(handle : GeosContextHandleT, g : GeosGeometry) : LibC::Char*
    fun geos_get_centroid = GEOSGetCentroid(g : GeosGeometry) : GeosGeometry
    fun geos_get_centroid_r = GEOSGetCentroid_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_get_exterior_ring = GEOSGetExteriorRing(g : GeosGeometry) : GeosGeometry
    fun geos_get_exterior_ring_r = GEOSGetExteriorRing_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_get_geometry_n = GEOSGetGeometryN(g : GeosGeometry, n : LibC::Int) : GeosGeometry
    fun geos_get_geometry_n_r = GEOSGetGeometryN_r(handle : GeosContextHandleT, g : GeosGeometry, n : LibC::Int) : GeosGeometry
    fun geos_get_interior_ring_n = GEOSGetInteriorRingN(g : GeosGeometry, n : LibC::Int) : GeosGeometry
    fun geos_get_interior_ring_n_r = GEOSGetInteriorRingN_r(handle : GeosContextHandleT, g : GeosGeometry, n : LibC::Int) : GeosGeometry
    fun geos_get_num_coordinates = GEOSGetNumCoordinates(g : GeosGeometry) : LibC::Int
    fun geos_get_num_coordinates_r = GEOSGetNumCoordinates_r(handle : GeosContextHandleT, g : GeosGeometry) : LibC::Int
    fun geos_get_num_geometries = GEOSGetNumGeometries(g : GeosGeometry) : LibC::Int
    fun geos_get_num_geometries_r = GEOSGetNumGeometries_r(handle : GeosContextHandleT, g : GeosGeometry) : LibC::Int
    fun geos_get_num_interior_rings = GEOSGetNumInteriorRings(g : GeosGeometry) : LibC::Int
    fun geos_get_num_interior_rings_r = GEOSGetNumInteriorRings_r(handle : GeosContextHandleT, g : GeosGeometry) : LibC::Int
    fun geos_get_srid = GEOSGetSRID(g : GeosGeometry) : LibC::Int
    fun geos_get_srid_r = GEOSGetSRID_r(handle : GeosContextHandleT, g : GeosGeometry) : LibC::Int
    fun geos_get_wkb_byte_order = GEOS_getWKBByteOrder : LibC::Int
    fun geos_get_wkb_byte_order_r = GEOS_getWKBByteOrder_r(handle : GeosContextHandleT) : LibC::Int
    fun geos_get_wkb_output_dims = GEOS_getWKBOutputDims : LibC::Int
    fun geos_get_wkb_output_dims_r = GEOS_getWKBOutputDims_r(handle : GeosContextHandleT) : LibC::Int
    fun geos_has_z = GEOSHasZ(g : GeosGeometry) : LibC::Char
    fun geos_has_z_r = GEOSHasZ_r(handle : GeosContextHandleT, g : GeosGeometry) : LibC::Char
    fun geos_hausdorff_distance = GEOSHausdorffDistance(g1 : GeosGeometry, g2 : GeosGeometry, dist : LibC::Double*) : LibC::Int
    fun geos_hausdorff_distance_densify = GEOSHausdorffDistanceDensify(g1 : GeosGeometry, g2 : GeosGeometry, densify_frac : LibC::Double, dist : LibC::Double*) : LibC::Int
    fun geos_hausdorff_distance_densify_r = GEOSHausdorffDistanceDensify_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry, densify_frac : LibC::Double, dist : LibC::Double*) : LibC::Int
    fun geos_hausdorff_distance_r = GEOSHausdorffDistance_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry, dist : LibC::Double*) : LibC::Int
    fun geos_init_r = GEOS_init_r : GeosContextHandleT
    fun geos_interpolate = GEOSInterpolate(g : GeosGeometry, d : LibC::Double) : GeosGeometry
    fun geos_interpolate_normalized = GEOSInterpolateNormalized(g : GeosGeometry, d : LibC::Double) : GeosGeometry
    fun geos_interpolate_normalized_r = GEOSInterpolateNormalized_r(handle : GeosContextHandleT, g : GeosGeometry, d : LibC::Double) : GeosGeometry
    fun geos_interpolate_r = GEOSInterpolate_r(handle : GeosContextHandleT, g : GeosGeometry, d : LibC::Double) : GeosGeometry
    fun geos_interrupt_cancel = GEOS_interruptCancel
    fun geos_interrupt_register_callback = GEOS_interruptRegisterCallback(cb : (-> Void)) : (-> Void)
    fun geos_interrupt_request = GEOS_interruptRequest
    fun geos_intersection = GEOSIntersection(g1 : GeosGeometry, g2 : GeosGeometry) : GeosGeometry
    fun geos_intersection_prec = GEOSIntersectionPrec(g1 : GeosGeometry, g2 : GeosGeometry, grid_size : LibC::Double) : GeosGeometry
    fun geos_intersection_prec_r = GEOSIntersectionPrec_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry, grid_size : LibC::Double) : GeosGeometry
    fun geos_intersection_r = GEOSIntersection_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry) : GeosGeometry
    fun geos_intersects = GEOSIntersects(g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_intersects_r = GEOSIntersects_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_largest_empty_circle = GEOSLargestEmptyCircle(g : GeosGeometry, boundary : GeosGeometry, tolerance : LibC::Double) : GeosGeometry
    fun geos_largest_empty_circle_r = GEOSLargestEmptyCircle_r(handle : GeosContextHandleT, g : GeosGeometry, boundary : GeosGeometry, tolerance : LibC::Double) : GeosGeometry
    fun geos_length = GEOSLength(g : GeosGeometry, length : LibC::Double*) : LibC::Int
    fun geos_length_r = GEOSLength_r(handle : GeosContextHandleT, g : GeosGeometry, length : LibC::Double*) : LibC::Int
    fun geos_line_merge = GEOSLineMerge(g : GeosGeometry) : GeosGeometry
    fun geos_line_merge_r = GEOSLineMerge_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_make_valid = GEOSMakeValid(g : GeosGeometry) : GeosGeometry
    fun geos_make_valid_r = GEOSMakeValid_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_maximum_inscribed_circle = GEOSMaximumInscribedCircle(g : GeosGeometry, tolerance : LibC::Double) : GeosGeometry
    fun geos_maximum_inscribed_circle_r = GEOSMaximumInscribedCircle_r(handle : GeosContextHandleT, g : GeosGeometry, tolerance : LibC::Double) : GeosGeometry
    fun geos_minimum_bounding_circle = GEOSMinimumBoundingCircle(g : GeosGeometry, radius : LibC::Double*, center : GeosGeometry*) : GeosGeometry
    fun geos_minimum_bounding_circle_r = GEOSMinimumBoundingCircle_r(handle : GeosContextHandleT, g : GeosGeometry, radius : LibC::Double*, center : GeosGeometry*) : GeosGeometry
    fun geos_minimum_clearance = GEOSMinimumClearance(g : GeosGeometry, d : LibC::Double*) : LibC::Int
    fun geos_minimum_clearance_line = GEOSMinimumClearanceLine(g : GeosGeometry) : GeosGeometry
    fun geos_minimum_clearance_line_r = GEOSMinimumClearanceLine_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_minimum_clearance_r = GEOSMinimumClearance_r(handle : GeosContextHandleT, g : GeosGeometry, distance : LibC::Double*) : LibC::Int
    fun geos_minimum_rotated_rectangle = GEOSMinimumRotatedRectangle(g : GeosGeometry) : GeosGeometry
    fun geos_minimum_rotated_rectangle_r = GEOSMinimumRotatedRectangle_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_minimum_width = GEOSMinimumWidth(g : GeosGeometry) : GeosGeometry
    fun geos_minimum_width_r = GEOSMinimumWidth_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_nearest_points = GEOSNearestPoints(g1 : GeosGeometry, g2 : GeosGeometry) : GeosCoordSequence
    fun geos_nearest_points_r = GEOSNearestPoints_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry) : GeosCoordSequence
    fun geos_node = GEOSNode(g : GeosGeometry) : GeosGeometry
    fun geos_node_r = GEOSNode_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_normalize = GEOSNormalize(g : GeosGeometry) : LibC::Int
    fun geos_normalize_r = GEOSNormalize_r(handle : GeosContextHandleT, g : GeosGeometry) : LibC::Int
    fun geos_offset_curve = GEOSOffsetCurve(g : GeosGeometry, width : LibC::Double, quadsegs : LibC::Int, join_style : LibC::Int, mitre_limit : LibC::Double) : GeosGeometry
    fun geos_offset_curve_r = GEOSOffsetCurve_r(handle : GeosContextHandleT, g : GeosGeometry, width : LibC::Double, quadsegs : LibC::Int, join_style : LibC::Int, mitre_limit : LibC::Double) : GeosGeometry
    fun geos_orientation_index = GEOSOrientationIndex(ax : LibC::Double, ay : LibC::Double, bx : LibC::Double, by : LibC::Double, px : LibC::Double, py : LibC::Double) : LibC::Int
    fun geos_orientation_index_r = GEOSOrientationIndex_r(handle : GeosContextHandleT, ax : LibC::Double, ay : LibC::Double, bx : LibC::Double, by : LibC::Double, px : LibC::Double, py : LibC::Double) : LibC::Int
    fun geos_overlaps = GEOSOverlaps(g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_overlaps_r = GEOSOverlaps_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_point_on_surface = GEOSPointOnSurface(g : GeosGeometry) : GeosGeometry
    fun geos_point_on_surface_r = GEOSPointOnSurface_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_polygonize = GEOSPolygonize(geoms : GeosGeometry*, ngeoms : LibC::UInt) : GeosGeometry
    fun geos_polygonize_full = GEOSPolygonize_full(input : GeosGeometry, cuts : GeosGeometry*, dangles : GeosGeometry*, invalid : GeosGeometry*) : GeosGeometry
    fun geos_polygonize_full_r = GEOSPolygonize_full_r(handle : GeosContextHandleT, input : GeosGeometry, cuts : GeosGeometry*, dangles : GeosGeometry*, invalid_rings : GeosGeometry*) : GeosGeometry
    fun geos_polygonize_r = GEOSPolygonize_r(handle : GeosContextHandleT, geoms : GeosGeometry*, ngeoms : LibC::UInt) : GeosGeometry
    fun geos_polygonize_valid = GEOSPolygonize_valid(geoms : GeosGeometry*, ngeoms : LibC::UInt) : GeosGeometry
    fun geos_polygonize_valid_r = GEOSPolygonize_valid_r(handle : GeosContextHandleT, geoms : GeosGeometry*, ngems : LibC::UInt) : GeosGeometry
    fun geos_polygonizer_get_cut_edges = GEOSPolygonizer_getCutEdges(geoms : GeosGeometry*, ngeoms : LibC::UInt) : GeosGeometry
    fun geos_polygonizer_get_cut_edges_r = GEOSPolygonizer_getCutEdges_r(handle : GeosContextHandleT, geoms : GeosGeometry*, ngeoms : LibC::UInt) : GeosGeometry
    fun geos_prepare = GEOSPrepare(g : GeosGeometry) : GeosPreparedGeometry
    fun geos_prepare_r = GEOSPrepare_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosPreparedGeometry
    fun geos_prepared_contains = GEOSPreparedContains(pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_prepared_contains_properly = GEOSPreparedContainsProperly(pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_prepared_contains_properly_r = GEOSPreparedContainsProperly_r(handle : GeosContextHandleT, pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_prepared_contains_r = GEOSPreparedContains_r(handle : GeosContextHandleT, pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_prepared_covered_by = GEOSPreparedCoveredBy(pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_prepared_covered_by_r = GEOSPreparedCoveredBy_r(handle : GeosContextHandleT, pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_prepared_covers = GEOSPreparedCovers(pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_prepared_covers_r = GEOSPreparedCovers_r(handle : GeosContextHandleT, pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_prepared_crosses = GEOSPreparedCrosses(pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_prepared_crosses_r = GEOSPreparedCrosses_r(handle : GeosContextHandleT, pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_prepared_disjoint = GEOSPreparedDisjoint(pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_prepared_disjoint_r = GEOSPreparedDisjoint_r(handle : GeosContextHandleT, pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_prepared_distance = GEOSPreparedDistance(pg1 : GeosPreparedGeometry, g2 : GeosGeometry, dist : LibC::Double*) : LibC::Int
    fun geos_prepared_distance_r = GEOSPreparedDistance_r(handle : GeosContextHandleT, pg1 : GeosPreparedGeometry, g2 : GeosGeometry, dist : LibC::Double*) : LibC::Int
    fun geos_prepared_geom_destroy = GEOSPreparedGeom_destroy(g : GeosPreparedGeometry)
    fun geos_prepared_geom_destroy_r = GEOSPreparedGeom_destroy_r(handle : GeosContextHandleT, g : GeosPreparedGeometry)
    fun geos_prepared_intersects = GEOSPreparedIntersects(pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_prepared_intersects_r = GEOSPreparedIntersects_r(handle : GeosContextHandleT, pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_prepared_nearest_points = GEOSPreparedNearestPoints(pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : GeosCoordSequence
    fun geos_prepared_nearest_points_r = GEOSPreparedNearestPoints_r(handle : GeosContextHandleT, pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : GeosCoordSequence
    fun geos_prepared_overlaps = GEOSPreparedOverlaps(pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_prepared_overlaps_r = GEOSPreparedOverlaps_r(handle : GeosContextHandleT, pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_prepared_touches = GEOSPreparedTouches(pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_prepared_touches_r = GEOSPreparedTouches_r(handle : GeosContextHandleT, pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_prepared_within = GEOSPreparedWithin(pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_prepared_within_r = GEOSPreparedWithin_r(handle : GeosContextHandleT, pg1 : GeosPreparedGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_project = GEOSProject(g : GeosGeometry, p : GeosGeometry) : LibC::Double
    fun geos_project_normalized = GEOSProjectNormalized(g : GeosGeometry, p : GeosGeometry) : LibC::Double
    fun geos_project_normalized_r = GEOSProjectNormalized_r(handle : GeosContextHandleT, g : GeosGeometry, p : GeosGeometry) : LibC::Double
    fun geos_project_r = GEOSProject_r(handle : GeosContextHandleT, g : GeosGeometry, p : GeosGeometry) : LibC::Double
    fun geos_relate = GEOSRelate(g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char*
    fun geos_relate_boundary_node_rule = GEOSRelateBoundaryNodeRule(g1 : GeosGeometry, g2 : GeosGeometry, bnr : LibC::Int) : LibC::Char*
    fun geos_relate_boundary_node_rule_r = GEOSRelateBoundaryNodeRule_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry, bnr : LibC::Int) : LibC::Char*
    fun geos_relate_pattern = GEOSRelatePattern(g1 : GeosGeometry, g2 : GeosGeometry, pat : LibC::Char*) : LibC::Char
    fun geos_relate_pattern_match = GEOSRelatePatternMatch(mat : LibC::Char*, pat : LibC::Char*) : LibC::Char
    fun geos_relate_pattern_match_r = GEOSRelatePatternMatch_r(handle : GeosContextHandleT, mat : LibC::Char*, pat : LibC::Char*) : LibC::Char
    fun geos_relate_pattern_r = GEOSRelatePattern_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry, pat : LibC::Char*) : LibC::Char
    fun geos_relate_r = GEOSRelate_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char*
    fun geos_reverse = GEOSReverse(g : GeosGeometry) : GeosGeometry
    fun geos_reverse_r = GEOSReverse_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_segment_intersection = GEOSSegmentIntersection(ax0 : LibC::Double, ay0 : LibC::Double, ax1 : LibC::Double, ay1 : LibC::Double, bx0 : LibC::Double, by0 : LibC::Double, bx1 : LibC::Double, by1 : LibC::Double, cx : LibC::Double*, cy : LibC::Double*) : LibC::Int
    fun geos_segment_intersection_r = GEOSSegmentIntersection_r(ext_handle : GeosContextHandleT, ax0 : LibC::Double, ay0 : LibC::Double, ax1 : LibC::Double, ay1 : LibC::Double, bx0 : LibC::Double, by0 : LibC::Double, bx1 : LibC::Double, by1 : LibC::Double, cx : LibC::Double*, cy : LibC::Double*) : LibC::Int
    fun geos_set_srid = GEOSSetSRID(g : GeosGeometry, srid : LibC::Int)
    fun geos_set_srid_r = GEOSSetSRID_r(handle : GeosContextHandleT, g : GeosGeometry, srid : LibC::Int)
    fun geos_set_wkb_byte_order = GEOS_setWKBByteOrder(byte_order : LibC::Int) : LibC::Int
    fun geos_set_wkb_byte_order_r = GEOS_setWKBByteOrder_r(handle : GeosContextHandleT, byte_order : LibC::Int) : LibC::Int
    fun geos_set_wkb_output_dims = GEOS_setWKBOutputDims(new_dims : LibC::Int) : LibC::Int
    fun geos_set_wkb_output_dims_r = GEOS_setWKBOutputDims_r(handle : GeosContextHandleT, new_dims : LibC::Int) : LibC::Int
    fun geos_shared_paths = GEOSSharedPaths(g1 : GeosGeometry, g2 : GeosGeometry) : GeosGeometry
    fun geos_shared_paths_r = GEOSSharedPaths_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry) : GeosGeometry
    fun geos_simplify = GEOSSimplify(g : GeosGeometry, tolerance : LibC::Double) : GeosGeometry
    fun geos_simplify_r = GEOSSimplify_r(handle : GeosContextHandleT, g : GeosGeometry, tolerance : LibC::Double) : GeosGeometry
    fun geos_single_sided_buffer = GEOSSingleSidedBuffer(g : GeosGeometry, width : LibC::Double, quadsegs : LibC::Int, join_style : LibC::Int, mitre_limit : LibC::Double, left_side : LibC::Int) : GeosGeometry
    fun geos_single_sided_buffer_r = GEOSSingleSidedBuffer_r(handle : GeosContextHandleT, g : GeosGeometry, width : LibC::Double, quadsegs : LibC::Int, join_style : LibC::Int, mitre_limit : LibC::Double, left_side : LibC::Int) : GeosGeometry
    fun geos_snap = GEOSSnap(g1 : GeosGeometry, g2 : GeosGeometry, tolerance : LibC::Double) : GeosGeometry
    fun geos_snap_r = GEOSSnap_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry, tolerance : LibC::Double) : GeosGeometry
    fun geos_sym_difference = GEOSSymDifference(g1 : GeosGeometry, g2 : GeosGeometry) : GeosGeometry
    fun geos_sym_difference_prec = GEOSSymDifferencePrec(g1 : GeosGeometry, g2 : GeosGeometry, grid_size : LibC::Double) : GeosGeometry
    fun geos_sym_difference_prec_r = GEOSSymDifferencePrec_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry, grid_size : LibC::Double) : GeosGeometry
    fun geos_sym_difference_r = GEOSSymDifference_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry) : GeosGeometry
    fun geos_topology_preserve_simplify = GEOSTopologyPreserveSimplify(g : GeosGeometry, tolerance : LibC::Double) : GeosGeometry
    fun geos_topology_preserve_simplify_r = GEOSTopologyPreserveSimplify_r(handle : GeosContextHandleT, g : GeosGeometry, tolerance : LibC::Double) : GeosGeometry
    fun geos_touches = GEOSTouches(g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_touches_r = GEOSTouches_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_unary_union = GEOSUnaryUnion(g : GeosGeometry) : GeosGeometry
    fun geos_unary_union_prec = GEOSUnaryUnionPrec(g : GeosGeometry, grid_size : LibC::Double) : GeosGeometry
    fun geos_unary_union_prec_r = GEOSUnaryUnionPrec_r(handle : GeosContextHandleT, g : GeosGeometry, grid_size : LibC::Double) : GeosGeometry
    fun geos_unary_union_r = GEOSUnaryUnion_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_union = GEOSUnion(g1 : GeosGeometry, g2 : GeosGeometry) : GeosGeometry
    fun geos_union_cascaded = GEOSUnionCascaded(g : GeosGeometry) : GeosGeometry
    fun geos_union_cascaded_r = GEOSUnionCascaded_r(handle : GeosContextHandleT, g : GeosGeometry) : GeosGeometry
    fun geos_union_prec = GEOSUnionPrec(g1 : GeosGeometry, g2 : GeosGeometry, grid_size : LibC::Double) : GeosGeometry
    fun geos_union_prec_r = GEOSUnionPrec_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry, grid_size : LibC::Double) : GeosGeometry
    fun geos_union_r = GEOSUnion_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry) : GeosGeometry
    fun geos_voronoi_diagram = GEOSVoronoiDiagram(g : GeosGeometry, env : GeosGeometry, tolerance : LibC::Double, only_edges : LibC::Int) : GeosGeometry
    fun geos_voronoi_diagram_r = GEOSVoronoiDiagram_r(ext_handle : GeosContextHandleT, g : GeosGeometry, env : GeosGeometry, tolerance : LibC::Double, only_edges : LibC::Int) : GeosGeometry
    fun geos_within = GEOSWithin(g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geos_within_r = GEOSWithin_r(handle : GeosContextHandleT, g1 : GeosGeometry, g2 : GeosGeometry) : LibC::Char
    fun geosst_rtree_create = GEOSSTRtree_create(node_capacity : LibC::SizeT) : GeosstRtree
    fun geosst_rtree_create_r = GEOSSTRtree_create_r(handle : GeosContextHandleT, node_capacity : LibC::SizeT) : GeosstRtree
    fun geosst_rtree_destroy = GEOSSTRtree_destroy(tree : GeosstRtree)
    fun geosst_rtree_destroy_r = GEOSSTRtree_destroy_r(handle : GeosContextHandleT, tree : GeosstRtree)
    fun geosst_rtree_insert = GEOSSTRtree_insert(tree : GeosstRtree, g : GeosGeometry, item : Void*)
    fun geosst_rtree_insert_r = GEOSSTRtree_insert_r(handle : GeosContextHandleT, tree : GeosstRtree, g : GeosGeometry, item : Void*)
    fun geosst_rtree_iterate = GEOSSTRtree_iterate(tree : GeosstRtree, callback : GeosQueryCallback, userdata : Void*)
    fun geosst_rtree_iterate_r = GEOSSTRtree_iterate_r(handle : GeosContextHandleT, tree : GeosstRtree, callback : GeosQueryCallback, userdata : Void*)
    fun geosst_rtree_nearest = GEOSSTRtree_nearest(tree : GeosstRtree, geom : GeosGeometry) : GeosGeometry
    fun geosst_rtree_nearest_generic = GEOSSTRtree_nearest_generic(tree : GeosstRtree, item : Void*, item_envelope : GeosGeometry, distancefn : GeosDistanceCallback, userdata : Void*) : Void*
    fun geosst_rtree_nearest_generic_r = GEOSSTRtree_nearest_generic_r(handle : GeosContextHandleT, tree : GeosstRtree, item : Void*, item_envelope : GeosGeometry, distancefn : GeosDistanceCallback, userdata : Void*) : Void*
    fun geosst_rtree_nearest_r = GEOSSTRtree_nearest_r(handle : GeosContextHandleT, tree : GeosstRtree, geom : GeosGeometry) : GeosGeometry
    fun geosst_rtree_query = GEOSSTRtree_query(tree : GeosstRtree, g : GeosGeometry, callback : GeosQueryCallback, userdata : Void*)
    fun geosst_rtree_query_r = GEOSSTRtree_query_r(handle : GeosContextHandleT, tree : GeosstRtree, g : GeosGeometry, callback : GeosQueryCallback, userdata : Void*)
    fun geosst_rtree_remove = GEOSSTRtree_remove(tree : GeosstRtree, g : GeosGeometry, item : Void*) : LibC::Char
    fun geosst_rtree_remove_r = GEOSSTRtree_remove_r(handle : GeosContextHandleT, tree : GeosstRtree, g : GeosGeometry, item : Void*) : LibC::Char
    fun geoswkb_reader_create = GEOSWKBReader_create : GeoswkbReader
    fun geoswkb_reader_create_r = GEOSWKBReader_create_r(handle : GeosContextHandleT) : GeoswkbReader
    fun geoswkb_reader_destroy = GEOSWKBReader_destroy(reader : GeoswkbReader)
    fun geoswkb_reader_destroy_r = GEOSWKBReader_destroy_r(handle : GeosContextHandleT, reader : GeoswkbReader)
    fun geoswkb_reader_read = GEOSWKBReader_read(reader : GeoswkbReader, wkb : UInt8*, size : LibC::SizeT) : GeosGeometry
    fun geoswkb_reader_read_hex = GEOSWKBReader_readHEX(reader : GeoswkbReader, hex : UInt8*, size : LibC::SizeT) : GeosGeometry
    fun geoswkb_reader_read_hex_r = GEOSWKBReader_readHEX_r(handle : GeosContextHandleT, reader : GeoswkbReader, hex : UInt8*, size : LibC::SizeT) : GeosGeometry
    fun geoswkb_reader_read_r = GEOSWKBReader_read_r(handle : GeosContextHandleT, reader : GeoswkbReader, wkb : UInt8*, size : LibC::SizeT) : GeosGeometry
    fun geoswkb_writer_create = GEOSWKBWriter_create : GeoswkbWriter
    fun geoswkb_writer_create_r = GEOSWKBWriter_create_r(handle : GeosContextHandleT) : GeoswkbWriter
    fun geoswkb_writer_destroy = GEOSWKBWriter_destroy(writer : GeoswkbWriter)
    fun geoswkb_writer_destroy_r = GEOSWKBWriter_destroy_r(handle : GeosContextHandleT, writer : GeoswkbWriter)
    fun geoswkb_writer_get_byte_order = GEOSWKBWriter_getByteOrder(writer : GeoswkbWriter) : LibC::Int
    fun geoswkb_writer_get_byte_order_r = GEOSWKBWriter_getByteOrder_r(handle : GeosContextHandleT, writer : GeoswkbWriter) : LibC::Int
    fun geoswkb_writer_get_include_srid = GEOSWKBWriter_getIncludeSRID(writer : GeoswkbWriter) : LibC::Char
    fun geoswkb_writer_get_include_srid_r = GEOSWKBWriter_getIncludeSRID_r(handle : GeosContextHandleT, writer : GeoswkbWriter) : LibC::Char
    fun geoswkb_writer_get_output_dimension = GEOSWKBWriter_getOutputDimension(writer : GeoswkbWriter) : LibC::Int
    fun geoswkb_writer_get_output_dimension_r = GEOSWKBWriter_getOutputDimension_r(handle : GeosContextHandleT, writer : GeoswkbWriter) : LibC::Int
    fun geoswkb_writer_set_byte_order = GEOSWKBWriter_setByteOrder(writer : GeoswkbWriter, byte_order : LibC::Int)
    fun geoswkb_writer_set_byte_order_r = GEOSWKBWriter_setByteOrder_r(handle : GeosContextHandleT, writer : GeoswkbWriter, byte_order : LibC::Int)
    fun geoswkb_writer_set_include_srid = GEOSWKBWriter_setIncludeSRID(writer : GeoswkbWriter, write_srid : LibC::Char)
    fun geoswkb_writer_set_include_srid_r = GEOSWKBWriter_setIncludeSRID_r(handle : GeosContextHandleT, writer : GeoswkbWriter, write_srid : LibC::Char)
    fun geoswkb_writer_set_output_dimension = GEOSWKBWriter_setOutputDimension(writer : GeoswkbWriter, new_dimension : LibC::Int)
    fun geoswkb_writer_set_output_dimension_r = GEOSWKBWriter_setOutputDimension_r(handle : GeosContextHandleT, writer : GeoswkbWriter, new_dimension : LibC::Int)
    fun geoswkb_writer_write = GEOSWKBWriter_write(writer : GeoswkbWriter, g : GeosGeometry, size : LibC::SizeT*) : UInt8*
    fun geoswkb_writer_write_hex = GEOSWKBWriter_writeHEX(writer : GeoswkbWriter, g : GeosGeometry, size : LibC::SizeT*) : UInt8*
    fun geoswkb_writer_write_hex_r = GEOSWKBWriter_writeHEX_r(handle : GeosContextHandleT, writer : GeoswkbWriter, g : GeosGeometry, size : LibC::SizeT*) : UInt8*
    fun geoswkb_writer_write_r = GEOSWKBWriter_write_r(handle : GeosContextHandleT, writer : GeoswkbWriter, g : GeosGeometry, size : LibC::SizeT*) : UInt8*
    fun geoswkt_reader_create = GEOSWKTReader_create : GeoswktReader
    fun geoswkt_reader_create_r = GEOSWKTReader_create_r(handle : GeosContextHandleT) : GeoswktReader
    fun geoswkt_reader_destroy = GEOSWKTReader_destroy(reader : GeoswktReader)
    fun geoswkt_reader_destroy_r = GEOSWKTReader_destroy_r(handle : GeosContextHandleT, reader : GeoswktReader)
    fun geoswkt_reader_read = GEOSWKTReader_read(reader : GeoswktReader, wkt : LibC::Char*) : GeosGeometry
    fun geoswkt_reader_read_r = GEOSWKTReader_read_r(handle : GeosContextHandleT, reader : GeoswktReader, wkt : LibC::Char*) : GeosGeometry
    fun geoswkt_writer_create = GEOSWKTWriter_create : GeoswktWriter
    fun geoswkt_writer_create_r = GEOSWKTWriter_create_r(handle : GeosContextHandleT) : GeoswktWriter
    fun geoswkt_writer_destroy = GEOSWKTWriter_destroy(writer : GeoswktWriter)
    fun geoswkt_writer_destroy_r = GEOSWKTWriter_destroy_r(handle : GeosContextHandleT, writer : GeoswktWriter)
    fun geoswkt_writer_get_output_dimension = GEOSWKTWriter_getOutputDimension(writer : GeoswktWriter) : LibC::Int
    fun geoswkt_writer_get_output_dimension_r = GEOSWKTWriter_getOutputDimension_r(handle : GeosContextHandleT, writer : GeoswktWriter) : LibC::Int
    fun geoswkt_writer_set_old3_d = GEOSWKTWriter_setOld3D(writer : GeoswktWriter, use_old3_d : LibC::Int)
    fun geoswkt_writer_set_old3_d_r = GEOSWKTWriter_setOld3D_r(handle : GeosContextHandleT, writer : GeoswktWriter, use_old3_d : LibC::Int)
    fun geoswkt_writer_set_output_dimension = GEOSWKTWriter_setOutputDimension(writer : GeoswktWriter, dim : LibC::Int)
    fun geoswkt_writer_set_output_dimension_r = GEOSWKTWriter_setOutputDimension_r(handle : GeosContextHandleT, writer : GeoswktWriter, dim : LibC::Int)
    fun geoswkt_writer_set_rounding_precision = GEOSWKTWriter_setRoundingPrecision(writer : GeoswktWriter, precision : LibC::Int)
    fun geoswkt_writer_set_rounding_precision_r = GEOSWKTWriter_setRoundingPrecision_r(handle : GeosContextHandleT, writer : GeoswktWriter, precision : LibC::Int)
    fun geoswkt_writer_set_trim = GEOSWKTWriter_setTrim(writer : GeoswktWriter, trim : LibC::Char)
    fun geoswkt_writer_set_trim_r = GEOSWKTWriter_setTrim_r(handle : GeosContextHandleT, writer : GeoswktWriter, trim : LibC::Char)
    fun geoswkt_writer_write = GEOSWKTWriter_write(writer : GeoswktWriter, g : GeosGeometry) : LibC::Char*
    fun geoswkt_writer_write_r = GEOSWKTWriter_write_r(handle : GeosContextHandleT, writer : GeoswktWriter, g : GeosGeometry) : LibC::Char*
    type GeosBufferParams = Void*
    type GeosContextHandleT = Void*
    type GeosCoordSequence = Void*
    type GeosGeometry = Void*
    type GeosPreparedGeometry = Void*
    type GeosstRtree = Void*
    type GeoswkbReader = Void*
    type GeoswkbWriter = Void*
    type GeoswktReader = Void*
    type GeoswktWriter = Void*
  end
end
